(load "~/quicklisp/setup.lisp")
(ql:quickload :rutils)
(defpackage #:aoc-2018-day2 (:use #:cl #:rutils #:named-readtables))
(in-package #:aoc-2018-day2)
(in-readtable rutils-readtable)

(defconstant *box-ids*
  '("efmyhuxcqqldtwjzvisepargvo"
    "efuyhuxckqldtwjrvrsbpargno"
    "efmyhuxckqlxtwjxvisbpargoo"
    "efmyhuxczqbdtwjzvisbpargjo"
    "efmyhugckqldtwjzvisfpargnq"
    "tfmyhuxckqljtwjzvisbpargko"
    "efmyhuxckqldtvuzvisbpavgno"
    "efmyhufcrqldtwjzvishpargno"
    "tfmyhuxbkqlduwjzvisbpargno"
    "efayhtxckqldbwjzvisbpargno"
    "efgyhuxckuldtwjzvisbpardno"
    "efmyhuxckuldtwizvisbpargqo"
    "efmyhuxcknldtjjzvihbpargno"
    "efmyhuxcnqddtwjzvisbpafgno"
    "efmyhubokqldtwjzvisbpargdo"
    "efmhhuxckqldtwdzvisbpjrgno"
    "efmyhuxckqldtwjrcisbpargny"
    "efmyhuxckqsdtwjzlisbpargng"
    "effyhuxckqlqtwjzjisbpargno"
    "nfmyhjxckqldtwjzcisbpargno"
    "efmyhvxckqldtwszvwsbpargno"
    "efmyhuxckqldtwutvisbpprgno"
    "kfmyhuxckqldtwzuvisbpargno"
    "efhyhtxckqldtwjmvisbpargno"
    "efmyhuhckqldtwjzvisbpxwgno"
    "efmyhuxcfqldtrjzvitbpargno"
    "efmyhudckqldtwjfvisbparvno"
    "ekmyhuxckqlstwjzvisbdargno"
    "efmyhuxckqlxtwjftisbpargno"
    "etsyhuxckqldtwjzvisbpargnf"
    "exmyhusckqldtwjzvisbpakgno"
    "efmyhubckqlrtljzvisbpargno"
    "efmyhuxckwldtwjovizbpargno"
    "efmyhulckqzdtwjzvisbpargpo"
    "efmyhuxckbcdlwjzvisbpargno"
    "zfmyhulckqbdtwjzvisbpargno"
    "efmyquxckfldtwazvisbpargno"
    "efxyhuxakqldtwjzvisupargno"
    "efmlhuxckkedtwjzvisbpargno"
    "efhyhuxwkqldtwjzvisbparjno"
    "efmyhuxfkqldtwjzvisvparyno"
    "efmyhuxckqfdtijzvisblargno"
    "efmyhuxckqldtfjzvisbwhrgno"
    "efmymuxcknldtwzzvisbpargno"
    "eomybuxckqldtwkzvisbpargno"
    "pfmyhuxckqldtwgzvasbpargno"
    "vfmyhuxcoqldtwjzvisbparvno"
    "eflyhuxckqldtwjzvirypargno"
    "efmyvuxckqldtwizvisbpaqgno"
    "epmyhuxckqldtwjzvesbparpno"
    "efoyhuxckoldtwjmvisbpargno"
    "efmyhuxckqydtwpzvisbpaqgno"
    "efmyhuxckqldezbzvisbpargno"
    "efmyhuxckqldtwjzvisboalxno"
    "efmyhuxckqldtwuzvipbjargno"
    "efmymuxcuqldtwjzvasbpargno"
    "jfmyhuxckqldtwjzvzsbpargdo"
    "nfmyhuxckqlntsjzvisbpargno"
    "efmxhuxckqgdtwjzvisbparjno"
    "efmyhuxckpldtpjzvpsbpargno"
    "efmyhuxcyqldtwjhvisbpargqo"
    "efmyhexgkqydtwjzvisbpargno"
    "ffmyhuxckqldtwjzvisbpafgnk"
    "efmyfuxckqldtwjpvisbpartno"
    "efmyhoxckcmdtwjzvisbpargno"
    "efmyhuxxkqldtwjzviabparyno"
    "jfmyhuxakqldtwgzvisbpargno"
    "efmjhuxckqcdtwjzvisbjargno"
    "efmyhuxccqldtwjzxisbxargno"
    "efmyhurckqldiwjzvrsbpargno"
    "efmyhuxckasdtwjzvisboargno"
    "efmyhvxckmldtwjgvisbpargno"
    "efmyhuxckoldtwjuvisbpardno"
    "efmyduxckqldtwjgvzsbpargno"
    "ejmyhuxckqldtwbzvisbpargnb"
    "efmymuxchqldtwjzvibbpargno"
    "efmyhjxckqldtwjgvinbpargno"
    "efmyhuxhyqldtwbzvisbpargno"
    "efmyhuxckqldtwjzvisbpzignq"
    "efmyuueckqldxwjzvisbpargno"
    "qfmyhyxckqldtwizvisbpargno"
    "efmyhupckqldtwjzvpgbpargno"
    "efmycuxckqldtwjzvfdbpargno"
    "efmyhugcrqldtwjfvisbpargno"
    "efmyhexckqldtwjzvischargno"
    "efmyhuxckqldtljzvasbpamgno"
    "efmyzdxckqldtwjovisbpargno"
    "efmyhuxccqldtwjzvdsbpaigno"
    "ufmyhuxekqldtwjzvisbpargne"
    "efmyhuxckqldfwozvisgpargno"
    "afmyhuackqldtwjzvisbdargno"
    "efmyauxckqldtwjzvisiparmno"
    "efmysuxckqldtwjzvisbeaggno"
    "efmyhuxckqldtwjzvisbgzigno"
    "efryhuxlkqldtwozvisbpargno"
    "lfmyhuxckqldtwjzvhsbparuno"
    "efmyhzxckqldswjzvisqpargno"
    "efmyhuxrkqldtwjzvisgpargco"
    "efmyhudckqldtwjzyisbkargno"
    "efmyhuacqqldtwjzviabpargno"
    "jfmyhuxckqldtwvzvicbpargno"
    "efmkhuxckqlftejzvisbpargno"
    "nfmyhuxckqldnwjzvisbxargno"
    "efmyhuxckqldtwjvvisjpyrgno"
    "efmyhuxcmxldtwjzvisbpargto"
    "efmyhuxckqldtwqbvpsbpargno"
    "efmyhuxckzldjwjzvisbplrgno"
    "efmywgxckqldtwxzvisbpargno"
    "efmsguxckqldhwjzvisbpargno"
    "nfmyhuxlkqldtwjzvisbgargno"
    "etmyhuxckqldtwjzvqsbptrgno"
    "efmyxuxckqldtfjzvisbyargno"
    "cfmihuxckqldtwjzvisbpargnf"
    "jfzyhuxckqldtwjzviscpargno"
    "efmyhuxckqldtmjzvisbpbzgno"
    "bfmyhuzckqldcwjzvisbpargno"
    "efmyhuxckqldtmjzvmslpargno"
    "efqyvuxckqldtwazvisbpargno"
    "efmecrxckqldtwjzvisbpargno"
    "efmyhuuckqldtwjzvisrpargnt"
    "efmphuxckqldtwjzvisbparmho"
    "ifmyhuxckqldtwjzvismpsrgno"
    "efmyhuookqldywjzvisbpargno"
    "efmyhfxckyldtwjnvisbpargno"
    "efmyhxhckqldtwjzvisqpargno"
    "efryhuxcfqldtwjzvisbparkno"
    "efmyhutckqldpwjzvixbpargno"
    "efmyoukckqldtwjzvisbpargko"
    "efmyhuxckqldtwjzviseparynv"
    "efmyhuxcksldvwjzvisbnargno"
    "efmyhuxckqrdtwlzmisbpargno"
    "efmyhuxcwqldtwjzviqapargno"
    "eymyhuxckqrdtwkzvisbpargno"
    "efmyhuxckqldtwjzpisopargnj"
    "efmyhuxikqldtwjzvirupargno"
    "efmyhuxcuzldtnjzvisbpargno"
    "efmyhxxikqldtwjzvisbpalgno"
    "efmyhuxceqldtwjzvdsbparguo"
    "efmyhuxwkqldtwjmvisbparxno"
    "efmyhuxpkqldtwjzvisfpargfo"
    "efmyfuxckaldtwjzvirbpargno"
    "efmyhuxckqrdtwjzvismprrgno"
    "efmyhuxckqldzwjzvisbpnrgfo"
    "efmyhfuckqldtwjyvisipargno"
    "efmyhuxcpqlqfwjzvisbpargno"
    "efmyyuxckqldtwjzvrsepargno"
    "efmphuxckqlptqjzvisbpargno"
    "efmyhuxnfqldtwjzvisbpmrgno"
    "efmyhuxckqldtwjzkisnpnrgno"
    "mfmyhuxckqldtwjzvisbzarcno"
    "efmyhuxckqldtwlzviszpargwo"
    "efmytuxckqndtwjqvisbpargno"
    "efmyzuxckqldtwjzvisbaargjo"
    "efmihuxckqlutwjzvimbpargno"
    "efmyhuxckqldgwjzvixbparono"
    "tfmyduxckqldtyjzvisbpargno"
    "ejmyhuockqldtwjzvidbpargno"
    "efmyheyckqkdtwjzvisbpargno"
    "efmyhuxckqldtwjzoisbpargfj"
    "efqyhuxcxqldtwxzvisbpargno"
    "jfmyhaxckqldtwjzvisbvargno"
    "hfmyhqxckqldtwjzvisbparvno"
    "efmyhukckqlrtwjzvqsbpargno"
    "efmyhuxckqldvwmzvisbparrno"
    "efoyhuxckqldtwjzvilwpargno"
    "ejmyhuxckqldtwjzxisbprrgno"
    "efmyhuxckqldtsjzvisupdrgno"
    "efzyhjxckqldtwjzvisbpasgno"
    "ebmyhulckqldtwjzvisbpargnr"
    "efmyhuxcjqlntwjzqisbpargno"
    "efmlocxckqldtwjzvisbpargno"
    "efmyhuxckqldtwjzvizkpargnm"
    "ebmyhuxckqldtwjzvlfbpargno"
    "efmyhuxckqldtwjyvisbpjrgnq"
    "afmyhuxckqldtwjzvpsbpargnv"
    "efmyxuxckqwdzwjzvisbpargno"
    "efmyhuxskqlqthjzvisbpargno"
    "efmyhuxckqldtwdzvisbearglo"
    "mfmyhuxckqldtzjzvisbparggo"
    "efmyhuqckqodtwjzvisbpadgno"
    "efmyhuxctqldywjzvisspargno"
    "efmyhuxckqqdtwjnvisbporgno"
    "efmyhixckqldowjzvisbpaagno"
    "efmyhuxckqldtsszvisbpargns"
    "edmyhuxckqpdtwjzrisbpargno"
    "efsyhuxckqldtijzvisbparano"
    "efmyhuxckqxdzwjzviqbpargno"
    "efmyhuxckqldtwjzviqqpsrgno"
    "efmyhuockqlatwjzvisbpargho"
    "efmyhuxckqldtwjzvishkavgno"
    "vfmyhuxckqldtwjzvksbaargno"
    "efmahuxckqudtwbzvisbpargno"
    "ewmyhixckqudtwjzvisbpargno"
    "efmywuxczqldtwjzvisbpargao"
    "efmyhuqjkqldtwyzvisbpargno"
    "efmyhuxekqldtwjzmksbpargno"
    "efmyhuxcoqtdtwjzvinbpargno"
    "ebmyhuxkkqldtwjzvisbdargno"
    "ecmyhnxckqldtwnzvisbpargno"
    "efmyhuxbkqldtwjzvksbpaigno"
    "efayhuxckqidtwjzvisbpavgno"
    "efmrhuxckqldswjzvisbpaugno"
    "efmyhuuckqldtwjyvisipargno"
    "xfmyhuxckqldawjzvosbpargno"
    "efmyhuxckklhtwjzvisbpargnq"
    "efmyhmxcaqldzwjzvisbpargno"
    "efiyhuxcksldtwjzvisbpamgno"
    "zfmyhuzckqldtwjzvisbparhno"
    "efmyhuxckqlvtwjdvisbparsno"
    "efmyhmxckaldtwjzmisbpargno"
    "efmysuxcqoldtwjzvisbpargno"
    "efmyhuxckqldtwjzvisbsargrb"
    "effyhuxckqldtwjzvisbpwfgno"
    "efmyhuxclqmdtwjzxisbpargno"
    "edmohuxckqldtwjziisbpargno"
    "efmyhuxckpldtwjzviubpaegno"
    "efmyhuxcpqldtwjzjimbpargno"
    "ehmyhuxckqldtwjzsisbpargnq"
    "efmyhcxcdqldtwjzvisbqargno"
    "efmjhuxckqldmwjzviybpargno"
    "efeyhzxckqlxtwjzvisbpargno"
    "efmyhuxczqadtwazvisbpargno"
    "efmahuxckqldtwjzvisbpafgnl"
    "efmyouxckqldtwjzvizbpacgno"
    "emmrhuxckqldtwjzvisqpargno"
    "exmyhuxckqlftwjnvisbpargno"
    "efuyhuxckqldrwjzvisbpargnw"
    "efmywuxfkqldtwjztisbpargno"
    "efmyhuxdkqldtwjzvisbpqrzno"
    "eemyhuxckqldrwjzvisbpajgno"
    "efmyiuxckqldtbjzvrsbpargno"
    "eqmyhuxckqldlwjzfisbpargno"
    "efmyhuxckqlitwuzvisbpvrgno"
    "ecoyhuxckqldtwjzvishpargno"
    "efmyhuxckcldtwjzlisbparlno"
    "efmyhsxcknldtwjfvisbpargno"
    "efmyhuxckqldtwjrvosbpargbo"
    "enmehuxckzldtwjzvisbpargno"
    "hfmyhuxckqqdtwjzvisbpawgno"
    "efmyhufckcjdtwjzvisbpargno"
    "efmxhuxckqldthjzvisfpargno"
    "efmyaukckqldtwjsvisbpargno"
    "efmyhukckqldtwpzvisbpmrgno"
    "dfmyhuxckqldtwjzvisbvarmno"
    "afmbhuxckqldtwjzvssbpargno"
    "efmyhuxchqldtwezvisbpargzo"
    "efmphuxckqlxjwjzvisbpargno"
    "efhyxuxckqldtwjzvisbpargko"
    "sfmyhexckqldtwjzvisbqargno"
    "efmghuxckqldtwjzvitbparnno"))


(defun count-two-or-three-same-letters (string)
  (let ((str (coerce string 'list)))
    (loop
       :with count-2 :and count-3 :and current-count := 0
       :for (a b) :on (sort str #'char<) :by #'cdr
       :if (and a b (char= a b))
       :do
         (incf current-count)
       :else
       :do
         (case current-count
           (1 (setf count-2 t))
           (2 (setf count-3 t)))
         (setf current-count 0)
       :finally
         (return (cons count-2 count-3)))))

(loop
  :with two-letter-count := 0 :and three-letter-count := 0
  :for id :in *box-ids*
  :do
     (destructuring-bind (twos . threes) (count-two-or-three-same-letters id)
       (when twos (incf two-letter-count))
       (when threes (incf three-letter-count)))
  :finally (return (* three-letter-count two-letter-count))) ;; => 7808

(defun string-difference (str1 str2)
  (loop :for c1 :across str1
        :for c2 :across str2
        :count (char/= c1 c2)))

(defun string-difference (str1 str2)
  (count-if-not
   (lambda (pair) (eql (car pair) (cadr pair)))
   (rutils:zip* (coerce str1 'list) (coerce str2 'list))))

(string-difference "abc" "ab")

(loop :for (head . tail) :on *box-ids*
      :do (let ((pairs (mapcar ^(list (string-difference head %) head %) tail)))
            (when-it (find-if ^(= (car %) 1) pairs)
              (when (consp it)
                (return it)))))
;; => (1 "efmyhfuckqldtwjyvisipargno" "efmyhuuckqldtwjyvisipargno")
